name: CI

on:
  schedule:
    # Cron job: runs every day at 3:30 PM UTC
    - cron: '41 14 * * *'

concurrency:
  group: ${{ github.run_id }}
  cancel-in-progress: true

env:
  CI_FAILFAST_TEST_LEAVE_DANGLING: 1  # Prevent GHA from killing the CI script itself on error
  MAKEJOBS: '-j7'

jobs:
  test-each-commit:
    name: 'Bitcoin_core'
    runs-on: self-hosted  # Use self-hosted runner with label 'Linux'
    timeout-minutes: 360  # Set maximum job time to 6 hours
    env:
      MAX_COUNT: 6  # Limit the number of commits to test

    steps:
      - name: Determine fetch depth
        run: echo "FETCH_DEPTH=10" >> "$GITHUB_ENV"  # Adjust as needed
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch the entire history
#change the git repository 
      - name: Clone Another Repository
        run: git clone git@github.com:vlinderlabs/Test-Gitactions-.git Test-Gitactions-
        shell: bash

      - name: List Files in Root Directory (Debugging)
        run: ls -la
        shell: bash

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang ccache build-essential libtool autotools-dev automake pkg-config \
            bsdmainutils python3-zmq libevent-dev libboost-dev libsqlite3-dev libdb++-dev systemtap-sdt-dev \
            libminiupnpc-dev libnatpmp-dev qtbase5-dev qttools5-dev qttools5-dev-tools qtwayland5 libqrencode-dev
        shell: bash
        continue-on-error: true  # Continue even if some packages fail to install

      - name: List Files in GUI-Dev Directory (Debugging)
        run: |
          cd Test-Gitactions-/gui-Dev
          ls -la  # Check for the presence of autogen.sh and other files in gui-Dev
        shell: bash

      - name: Set Executable Permissions for autogen.sh
        run: |
          cd Test-Gitactions-/gui-Dev
          chmod +x autogen.sh  # Make autogen.sh executable
        shell: bash

      - name: Change to Test-Gitactions-/gui-Dev directory
        run: cd Test-Gitactions-/gui-Dev
        shell: bash

      - name: Run autogen.sh
        run: |
          cd Test-Gitactions-/gui-Dev
          ./autogen.sh
        shell: bash
        continue-on-error: true  # If autogen fails, proceed to the next steps

      - name: Configure with incompatible BDB
        run: |
         cd Test-Gitactions-/gui-Dev
         CC=clang CXX=clang++ ./configure --with-incompatible-bdb
        shell: bash
        continue-on-error: true  # If configuration fails, proceed to the next steps

      - name: Clean build files
        run: |
         cd Test-Gitactions-/gui-Dev
         make clean
        shell: bash
        continue-on-error: true  # Continue even if compilation fails

      - name: Compile the project
        run: |
         cd Test-Gitactions-/gui-Dev
         make -j $(nproc)
        shell: bash
        continue-on-error: true  # Continue even if compilation fails

      - name: Run Unit Tests (main branch)
        if: github.ref == 'refs/heads/main'  # Run only if pushing to main branch
        run: |
          cd Test-Gitactions-/gui-Dev/QASE_API
          python3 unit_test_creator.py
        shell: bash

      - name: Run Functional Tests (develop branch)
        if: github.ref == 'refs/heads/develop'  # Run only if pushing to develop branch
        run: |
          cd Test-Gitactions-/gui-Dev/QASE_API
          python3 unit_test_creator.py  # Change to your functional test script
        shell: bash